# Generated by Django 4.1.2 on 2022-10-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deputado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_api",
                    models.PositiveIntegerField(verbose_name="Id na API da Câmara"),
                ),
                ("uri", models.URLField()),
                ("nome", models.CharField(max_length=255)),
                ("sigla_partido", models.CharField(max_length=10)),
                ("uri_partido", models.URLField()),
                ("sigla_uf", models.CharField(max_length=2)),
                ("id_legislatura", models.PositiveIntegerField()),
                ("url_foto", models.URLField()),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
    ]
